---
- name: nfs_mount
  hosts: all
  gather_facts: false
  tasks:
  - name: making nfs_ directory in client side
    file:
      path: /nfs1
      state: directory
  - name: restart nfs_ service
    service:
      name: nfs
      state: restarted
      enabled: yes
  - name: restart nfs_ server service
    service:
      name: nfs-server
      state: restarted
      enabled: yes
  - name: mount
    mount:
      src: 192.168.122.94:/nfs1
      path: /nfs1
      fstype: nfs
      state: mounted
