---
- name: nfs_mount
  hosts: all
  gather_facts: false
  tasks:
  - name: making nfs_ directory in client side
    file:
      path: /nfs1
      state: directory
  - name: restart nfs_ service
    service:
      name: nfs
      state: restarted
      enabled: yes
  - name: restart nfs_ server service
    service:
      name: nfs-server
      state: restarted
      enabled: yes
  - name: adding entry to fstab
    blockinfile:
      path: /etc/fstab
      block: |
        192.168.122.94:/nfs1    /nfs1   nfs     defaults        0       0 
  - name: mounting
    command: mount -a
